title: Hola, Soy Alfonso Yeste, soy Analista Digital enfocado al UX y CRO.
description: > # this means to ignore newlines until "baseurl:"
  Bienvenidos a mi blog personal donde comparto el conocimiento que he adquirido trabajando y experimentando.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alfonsoyeste.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alfonso Yeste
author-logo: sergiosusa_logo.jpg
author-img: sergio-susa.jpg # add your photo
about-author: ğŸ’» UX & CRO â€¢ ğŸ‘¨â€ğŸ« Profesor â€¢ ğŸ“» Podcaster â€¢ âœğŸ¼Intento de escritor 
social-twitter: sergiosusa # add your Twitter handle
social-facebook: sergiosusa # add your Facebook handle
social-github: sergiosusa # add your Github handle
social-linkedin: sergiosusa # add your Linkedin handle
social-email: sergio@sergiosusa.com # add your Email address

# Disqus
discus-identifier: alfonso-yeste # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
